controller_manager:
  ros__parameters:
    /my_drone/joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    /my_drone/rotor_0_joint_controller:
      type: effort_controllers/JointEffortController
      joint: rotor_0_joint
      pid: {p: 100.0, i: 0.0, d: 10.0}

    /my_drone/rotor_1_joint_controller:
      type: effort_controllers/JointEffortController
      joint: rotor_1_joint
      pid: {p: 100.0, i: 0.0, d: 10.0}

    /my_drone/rotor_2_joint_controller:
      type: effort_controllers/JointEffortController
      joint: rotor_2_joint
      pid: {p: 100.0, i: 0.0, d: 10.0}

    /my_drone/rotor_3_joint_controller:
      type: effort_controllers/JointEffortController
      joint: rotor_3_joint
      pid: {p: 100.0, i: 0.0, d: 10.0}
